//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdülkadir_Şengül.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int No { get; set; }
        public string IP { get; set; }
        public string Tarayici { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Metot { get; set; }
        public string Parametre { get; set; }
        public Nullable<int> KullaniciNumara { get; set; }
    }
}
