//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdülkadir_Şengül.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.MakaleKategori = new HashSet<MakaleKategori>();
            this.MakaleYazar = new HashSet<MakaleYazar>();
        }
    
        public int No { get; set; }
        public string Ad { get; set; }
        public string YayinTarihi { get; set; }
        public Nullable<int> DergiNo { get; set; }
        public Nullable<int> MakaleTuruNo { get; set; }
        public Nullable<int> EndeksNo { get; set; }
        public string Özet { get; set; }
    
        public virtual Dergi Dergi { get; set; }
        public virtual Endeks Endeks { get; set; }
        public virtual MakaleTur MakaleTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MakaleKategori> MakaleKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MakaleYazar> MakaleYazar { get; set; }
    }
}
